package org.gingerjake.potatogame;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Scanner;

public class SaveSystem {
    static FileWriter saveWriter;
    static final File saveData = new File("save.txt");

    @SuppressWarnings("ResultOfMethodCallIgnored")
    public static void saveGame() throws IOException {
        if (!saveData.exists()) {
            saveData.createNewFile();

        }

        try {
            saveWriter = new FileWriter(saveData);
            saveWriter.write("WARNING: DO NOT EDIT THIS FILE UNLESS YOU KNOW WHAT YOU ARE DOING!");
            saveWriter.write("\nControlMode: " + Controls.controlMode);
            saveWriter.close();
            System.out.println("Game saved");
        } catch (IOException e) {
            e.printStackTrace();
        }
    }

    public static void loadGame() throws FileNotFoundException {
        if (saveData.exists()) {
            Scanner saveReader = new Scanner(saveData);
            while (saveReader.hasNextLine()) {
                String line = saveReader.nextLine();
                if(line.contains("ControlMode")) {
                    String[] splitLine = line.split(" ");
                    String value = splitLine[1];
                    Controls.controlMode = Integer.parseInt(value);
                    System.out.println("Loaded controlMode: " + Controls.controlMode);
                }
            }
        }
    }
}
